### ISSUE TITLE
Unable to Install Rails 5.2 on Ruby 2.5 due to Nokogiri Version Requirement

### ISSUE THREAD

**Issue by obahareth** [rails/rails-dom-testing#100]
The current Nokogiri version required is making installing Rails 5.2 on Ruby 2.5 fail because it's grabbing Nokogiri 1.13, and that requires Ruby versions >= 2.6

```sh
Gem::RuntimeRequirementNotMetError: nokogiri requires Ruby version < 3.2.dev, >=
2.6. The current ruby version is 2.5.0.
An error occurred while installing nokogiri (1.13.3), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.13.3' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rails was resolved to 5.2.7, which depends on
    actioncable was resolved to 5.2.7, which depends on
      actionpack was resolved to 5.2.7, which depends on
        actionview was resolved to 5.2.7, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri
```

**Comment by obahareth** [comment]
Just to note that this is currently breaking Ruby on [Rails's Ruby version requirement](https://rubygems.org/gems/rails/versions/5.2.7.1).

Rails 5.2 requires Ruby >= 2.2.2 but with this issue you're unable to run it unless you upgrade to Ruby 2.6.

**Comment by flavorjones** [comment]
Please see my comment at https://github.com/rails/rails/issues/45008#issuecomment-1115251830

**Comment by obahareth** [comment]
@flavorjones's linked comment helped me resolve the issue.
