### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails-dom-testing#101]
This gem hasn't been updated on Rubygems since 2017. There's been quite a few improvements since then: https://github.com/rails/rails-dom-testing/compare/v2.0.3...master - none of these would be included when creating a new Rails app.

Could we consider a new gem version?

**Comment by nflorentin** [comment]
+1
assert_select is a misleading name and has same name as capybara minitest assertion assert_select. 
That would be nice to have a new version.

**Comment by rafaelfranca** [comment]
Done
