### ISSUE TITLE
assert_select "foo", "x", count: 0 --- no longer works

### ISSUE THREAD

**Issue by michaeleconomy** [rails/rails-dom-testing#111]
### Steps to reproduce
After upgrading from rails 7.0.4 to 7.0.7

assert_select "foo", "x", count: 0 #no longer works
switching to:
assert_select "foo", text: "x", count: 0 #this has different behavior from the above statement

### Expected behavior
i want to test that there is no tag with the specified text.

### Actual behavior
I can no longer do this with assert_select on the new rails version.

**Comment by rafaelfranca** [comment]
`assert_select "foo", "x", count: 0`

Was always incorrect.

`assert_select "foo", text: "x", count: 0` is what you want. See documentation here https://github.com/rails/rails-dom-testing/blob/a14001a41d514ece1a7c4d03a1d9bc69edf677d1/lib/rails/dom/testing/assertions/selector_assertions.rb#L147

**Comment by michaeleconomy** [comment]
Right on, my bad.  Thanks guys!

**Comment by ccasabona** [comment]
Thanks for taking the time for a refresher course on this.
