### ISSUE TITLE
Fetching this gem is very slow

### ISSUE THREAD

**Issue by lion-man44** [rails/rails-dom-testing#119]
I've been using github actions and I just noticed fetching this gem is very slow.

```
#13 43.45 Installing counter_culture 3.5.2
#13 154.2 Fetching rails-dom-testing 2.2.0
```

Is that not happen other people's environment?
I'm just curious.

**Comment by flavorjones** [comment]
This gem is only 16kb and is hosted on rubygems.org, which this gem's maintainers do not control. If it is indeed slow (which your log snippet does not clearly show), please ask on another forum.

It's more likely that you're compiling a C extension somewhere in your bundle and that's introducing a delay. Consider that "fetching" is printed at the _start_ of fetching a gem.
