### ISSUE TITLE
Update dependency conflict

### ISSUE THREAD

**Issue by pencilcheck** [rails/rails-dom-testing#33]
Update dependency conflict:

```
Bundler could not find compatible versions for gem
"activesupport":
  In Gemfile:
    rails (= 4.2.0) ruby depends on
      activerecord (= 4.2.0) ruby depends on
        activesupport (= 4.2.0) ruby

    rails (= 4.2.0) ruby depends on
      actionmailer (= 4.2.0) ruby depends on
        rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
          activesupport (4.2.0.beta1)
```

Caused by this commit: https://github.com/rails/rails-dom-testing/commit/9b5d8e9ca86c6beac9f802c9459325e1b929d173

**Comment by kaspth** [comment]
The version constraint should be flexible enough to handle that scenario already.

Have you tried either `bundle update activesupport` or `bundle update rails-dom-testing`?

--
Kasper

**Comment by pencilcheck** [comment]
rails-dom-testing is not in Gemfile, so `bundle update rails-dom-testing` does not work.
And the other does not help the situation. Same problems.

**Comment by rafaelfranca** [comment]
Yeah, this is more a rubygems/bundler problem that an issue in the way we define the dependency. Just `bundle update rails` would work.

**Comment by pencilcheck** [comment]
It just doesn't work. I of course did that. And it just leads back to rails-dom-testing with the errors above.

**Comment by rafaelfranca** [comment]
I don't know if this is a Rubygems issue or bundler issue, but it is definitely in one of those.

**Comment by pencilcheck** [comment]
So you are saying you are able to upgrade to rails 4.2 from 4.1.x etc without seeing this errors? can you explain your steps?

**Comment by rafaelfranca** [comment]
Yes. Just change Rails version at gemfile and  bundle update rails worked fine to me.

**Comment by pencilcheck** [comment]
What's your ruby version?

**Comment by pencilcheck** [comment]
```
$ bundle update rails
Fetching source index from https://rails-assets.org/
Fetching source index from https://rubygems.org/
Resolving dependencies....
Bundler could not find compatible versions for gem
"activesupport":
  In Gemfile:
    rails (= 4.2.0) ruby depends on
      activesupport (= 4.2.0) ruby

    rails (= 4.2.0) ruby depends on
      actionmailer (= 4.2.0) ruby depends on
        rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
          activesupport (4.2.0.beta1)
```

**Comment by pencilcheck** [comment]
Also, what's the harm of changing just one line? It would save so many unnecessary time and debate and github issue tracker.

**Comment by rafaelfranca** [comment]
It is not just one line problem, it is a problem in one of the important
tools of the Ruby ecosystem. I can change that line but the bug will still
there and I really believe this bug need to be fixed on those libraries or
we can't work with pre versions when programming in Ruby.

**Comment by pencilcheck** [comment]
Well, it's not helping out anyone here with your speech here. Maybe submit a issue upstream and change the version then at least people with similar problems can upgrade to 4.2 without getting stuck.

**Comment by rafaelfranca** [comment]
Yeah, agree.

We need to investigate the cause to report upstream. Just changing the
dependency will not help with this and since I couldn't reproduce this
problem I thought you could find a way to reproduce and submit the issue
upstream.

**Comment by rafaelfranca** [comment]
About releasing yeah, I think it is better to do it. I just want to have
the original issue mapped and reported before we could move on.

Just be aware that this is not the only gem that you will find this
problem. Almost every gem Rails uses is pointing to pre releases and will
need to be changed, and that is a lot of work.

**Comment by pencilcheck** [comment]
I'm using ruby 2.1.3, I wonder what's your ruby version is. I am pretty sure I am using the latest bundler (1.7.12)

I don't know how to provide the environment in which the issue can be reproduced though. And where should I report to? bundler?

**Comment by rafaelfranca** [comment]
I'm using 2.1.5 and same bundler version. Which is your Rubygems version?
Maybe the problem is also there.

**Comment by pencilcheck** [comment]
My rubygem version is 2.4.5
