### ISSUE TITLE
https://github.com/kaspth/rails-dom-testing

### ISSUE THREAD

**Issue by voxik** [rails/rails-dom-testing#34]

**Comment by kaspth** [comment]
I don't understand what the issue is. Feel free to reopen when you can clarify this.

**Comment by voxik** [comment]
Interesting, I'm not aware that I submitted such issue ... but since I am in it, could you please clarify where is the canonical upstream repository? Is it your fork or this one?

**Comment by rafaelfranca** [comment]
@voxik this one

**Comment by voxik** [comment]
Could this be update then?

https://github.com/rails/rails-dom-testing/blob/master/rails-dom-testing.gemspec#L13

Thank you.

BTW It is interesting that the summary is longer than the description. May be you can swap them once you are in editing .gemspec file. Thx once again.
