### ISSUE TITLE
Make assert_select take selector as a Symbol

### ISSUE THREAD

**Issue by why-el** [rails/rails-dom-testing#40]
Is there any reason why the first argument to `assert_select` cannot be a symbol? Will submit a quick PR if none.

**Comment by kaspth** [comment]
To me it's more clear that it's a selector if it's just a string. I think the gains are too small versus the mental cost of treating something that's better contained in a string as a symbol. Thanks for the suggestion though! :smile:

**Comment by why-el** [comment]
Sure thing, I was just surprised since this is a fairly common Rails expectation, but I can see your point with selectors. Thanks for the prompt response.
