### ISSUE TITLE
assert_select_encoded can't handle escaped characters within XML

### ISSUE THREAD

**Issue by dnrce** [rails/rails-dom-testing#42]
Escaped characters within XML (as [required by the spec](http://www.w3.org/TR/REC-xml/#syntax)) aren't handled properly by `assert_select_encoded`. For example, no `p` element is found within the following:
```xml
<element>&lt;p&gt;Paragraph text&lt;/p&gt;</element>
```
The same content using CDATA has no issues.

See https://gist.github.com/dnrce/9e48173bda64ea1ee6ed to reproduce.

**Comment by kaspth** [comment]
This looks like escaped content and not encoded CDATA content. As far as I know, `assert_select_encoded` is only supposed to work on CDATA elements — see the tests here: https://github.com/rails/rails-dom-testing/blob/46591c734986b3f70baf35d16d677714ecb3de59/test/selector_assertions_test.rb#L235-L280.

**Comment by dnrce** [comment]
Escaped content is the default output of the Rails XML builder, so it seems like a miss to be unable to test that easily. I'll see if I can write a test case that uses the builder directly.

**Comment by dnrce** [comment]
@kaspth, I updated my gist to include tests based on `builder` output.

**Comment by dnrce** [comment]
I should also mention that I ran into this during a Rails 4.2 upgrade -- the version of the method built into Action Pack 4.1 has no trouble with this because it uses `CGI.unescapeHTML`. So although rails-dom-testing is new in the 4.2 ecosystem, in a way this is a regression.

https://github.com/rails/rails/blob/13dfc8fbdc273e11f28dffc2e3aca10cb43d3a82/actionpack/lib/action_dispatch/testing/assertions/selector.rb#L382
