### ISSUE TITLE
New release on RubyGems?

### ISSUE THREAD

**Issue by connorshea** [rails/rails-dom-testing#49]
I'd like to try out the Rails 5 release candidate, but this is blocking me. I'd prefer not to have to use a dozen+ gems directly from git repos, if possible.

**Comment by kaspth** [comment]
Done! https://rubygems.org/gems/rails-dom-testing/versions/2.0.0

Thanks for the reminder ❤️

**Comment by connorshea** [comment]
Thanks! :D

**Comment by connorshea** [comment]
@kaspth don't forget to tag the release on GitHub :)

**Comment by kaspth** [comment]
@connorshea I did forget, but did it now: https://github.com/rails/rails-dom-testing/releases/tag/v2.0.0 :)
