### ISSUE TITLE
Where can I read about changes between 1.0 and 2.0?

### ISSUE THREAD

**Issue by jaredbeck** [rails/rails-dom-testing#50]
I don't see any mention of 2.0 on https://github.com/rails/rails-dom-testing/releases, and I don't see a changelog. Sorry if it's there and I'm just not seeing it. Thanks.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails-dom-testing/releases/tag/v2.0.0

**Comment by kaspth** [comment]
I forgot to push the tag to my upstream git remote, I've added it now: https://github.com/rails/rails-dom-testing/releases/tag/v2.0.0

**Comment by jaredbeck** [comment]
Thanks Kasper
