### ISSUE TITLE
Gem dependency for Ruby 2.4 support

### ISSUE THREAD

**Issue by atitan** [rails/rails-dom-testing#59]
Hello,

Currently `rails-dom-testing` locks runtime dependency `nokogiri` at `~> 1.6.0`, however `nokogiri` needs to be at least `1.7.0` to support Ruby 2.4.

Please change the dependency target to fix this.

**Comment by rafaelfranca** [comment]
Thanks! It is already fixed on master.

**Comment by rafaelfranca** [comment]
And in the version 2.0.2
