### ISSUE TITLE
assert_select mutates the first string argument

### ISSUE THREAD

**Issue by obfuscoder** [rails/rails-dom-testing#69]
Using the new header `# frozen_string_literal: true` defines all strings as frozen. This is the recommended way in order to be ready for the transition to Ruby 3 where all strings will be immutable by default.

With that I got exceptions running code like this in my tests:

`assert_select +'a[href=?]', some_path`

It seems, assert_select mutates the first argument instead of dup'ing it first.

**Comment by obfuscoder** [comment]
Created https://github.com/rails/rails-dom-testing/issues/69

**Comment by obfuscoder** [comment]
There is no answer on this issue yet. Is this the right place or is this module maintained some place else now?

**Comment by kaspth** [comment]
Right place. Do submit a PR 😊

**Comment by mikegee** [comment]
#70 resolved this issue, right?

**Comment by kaspth** [comment]
It is. Thanks for checking!
